services:
  app:
    build: .
    container_name: containers_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:7.0
    container_name: containers_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=containers_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: containers_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge